In [1]:
import pandas as pd 
import numpy as np

import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [2]:
data=pd.read_csv("car_purchasing.csv",encoding='ISO-8859-1')

In [3]:
data.head()

,customer name,customer e-mail,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,Martina Avila,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,Harlan Barnes,eu.dolor@diam.co.uk,Belize,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,Naomi Rodriquez,vulputate.mauris.sagittis@ametconsectetueradip...,Algeria,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,Jade Cunningham,malesuada@dignissim.com,Cook Islands,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,Cedric Leach,felis.ullamcorper.viverra@egetmollislectus.net,Brazil,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248

In [4]:
data.tail()

,customer name,customer e-mail,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
495,Walter,ligula@Cumsociis.ca,Nepal,0,41.462515,71942.40291,6995.902524,541670.1016,48901.44342
496,Vanna,Cum.sociis.natoque@Sedmolestie.edu,Zimbabwe,1,37.642000,56039.49793,12301.456790,360419.0988,31491.41457
497,Pearl,penatibus.et@massanonante.com,Philippines,1,53.943497,68888.77805,10611.606860,764531.3203,64147.28888
498,Nell,Quisque.varius@arcuVivamussit.net,Botswana,1,59.160509,49811.99062,14013.034510,337826.6382,45442.15353
499,Marla,Camaron.marla@hotmail.com,marlal,1,46.731152,61370.67766,9391.341628,462946.4924,45107.22566

In [5]:
data.shape

(500, 9)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer name        500 non-null    object
 1   customer e-mail      500 non-null    object
 2   country              500 non-null    object
 3   gender               500 non-null    int64
 4   age                  500 non-null    float64
 5   annual Salary        500 non-null    float64
 6   credit card debt     500 non-null    float64
 7   net worth            500 non-null    float64
 8   car purchase amount  500 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 35.3+ KB

In [7]:
data.describe()

,gender,age,annual Salary,credit card debt,net worth,car purchase amount
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,0.506000,46.241674,62127.239608,9607.645049,431475.713625,44209.799218
std,0.500465,7.978862,11703.378228,3489.187973,173536.756340,10773.178744
min,0.000000,20.000000,20000.000000,100.000000,20000.000000,9000.000000
25%,0.000000,40.949969,54391.977195,7397.515792,299824.195900,37629.896040
50%,1.000000,46.049901,62915.497035,9655.035568,426750.120650,43997.783390
75%,1.000000,51.612263,70117.862005,11798.867487,557324.478725,51254.709517
max,1.000000,70.000000,100000.000000,20000.000000,1000000.000000,80000.000000

In [8]:
dt=data.copy(deep=True)

In [9]:
dt.columns

Index(['customer name', 'customer e-mail', 'country', 'gender', 'age',
       'annual Salary', 'credit card debt', 'net worth',
       'car purchase amount'],
      dtype='object')

In [10]:
dt.drop(["customer name","customer e-mail","country"],axis=1,inplace=True)

In [11]:
dt.head()

,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248

In [12]:
scaling_features=dt[['gender', 'age','annual Salary', 'credit card debt', 'net worth',]]
scaling_features

     gender        age  annual Salary  credit card debt    net worth
0         0  41.851720    62812.09301      11609.380910  238961.2505
1         0  40.870623    66646.89292       9572.957136  530973.9078
2         1  43.152897    53798.55112      11160.355060  638467.1773
3         1  58.271369    79370.03798      14426.164850  548599.0524
4         1  57.313749    59729.15130       5358.712177  560304.0671
..      ...        ...            ...               ...          ...
495       0  41.462515    71942.40291       6995.902524  541670.1016
496       1  37.642000    56039.49793      12301.456790  360419.0988
497       1  53.943497    68888.77805      10611.606860  764531.3203
498       1  59.160509    49811.99062      14013.034510  337826.6382
499       1  46.731152    61370.67766       9391.341628  462946.4924

[500 rows x 5 columns]

In [13]:
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
dt[['gender', 'age','annual Salary', 'credit card debt', 'net worth',]]=sc.fit_transform(scaling_features)

In [14]:
dt

,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,-1.012073,-0.550749,0.058576,0.574271,-1.110469,35321.45877
1,-1.012073,-0.673834,0.386570,-0.009951,0.573929,45115.52566
2,0.988071,-0.387508,-0.712361,0.445452,1.193976,42925.70921
3,0.988071,1.509206,1.474794,1.382369,0.675595,67422.36313
4,0.988071,1.389066,-0.205111,-1.218962,0.743113,55915.46248
...,...,...,...,...,...,...
495,-1.012073,-0.599577,0.839501,-0.749274,0.635628,48901.44342
496,0.988071,-1.078887,-0.520691,0.772819,-0.409872,31491.41457
497,0.988071,0.966245,0.578321,0.288023,1.921144,64147.28888
498,0.988071,1.620754,-1.053335,1.263847,-0.540190,45442.15353
499,0.988071,0.061408,-0.064709,-0.062055,0.181531,45107.22566

In [15]:
x=dt.iloc[:,:-1]
print(x)
y=dt.iloc[:,-1]
print(y)

       gender       age  annual Salary  credit card debt  net worth
0   -1.012073 -0.550749       0.058576          0.574271  -1.110469
1   -1.012073 -0.673834       0.386570         -0.009951   0.573929
2    0.988071 -0.387508      -0.712361          0.445452   1.193976
3    0.988071  1.509206       1.474794          1.382369   0.675595
4    0.988071  1.389066      -0.205111         -1.218962   0.743113
..        ...       ...            ...               ...        ...
495 -1.012073 -0.599577       0.839501         -0.749274   0.635628
496  0.988071 -1.078887      -0.520691          0.772819  -0.409872
497  0.988071  0.966245       0.578321          0.288023   1.921144
498  0.988071  1.620754      -1.053335          1.263847  -0.540190
499  0.988071  0.061408      -0.064709         -0.062055   0.181531

[500 rows x 5 columns]
0      35321.45877
1      45115.52566
2      42925.70921
3      67422.36313
4      55915.46248
          ...
495    48901.44342
496    31491.41457
497    64147.28888
498    45442.15353
499    45107.22566
Name: car purchase amount, Length: 500, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=0)

In [40]:
ann=Sequential()

ann.add(Dense(units=6))
ann.add(Dense(units=8))
ann.add(Dense(units=6))
ann.add(Dense(units=1,activation="linear"))

ann.compile(optimizer="adam",loss="mean_squared_error",metrics=["mean_absolute_error"])

ann.fit(xtrain,ytrain,batch_size=10,epochs=300)

ypred=ann.predict(xtest)

Epoch 1/300
35/35 [==============================] - 1s 2ms/step - loss: 2056666112.0000 - mean_absolute_error: 44033.2930
Epoch 2/300
35/35 [==============================] - 0s 3ms/step - loss: 2056621312.0000 - mean_absolute_error: 44032.8789
Epoch 3/300
35/35 [==============================] - 0s 2ms/step - loss: 2056557184.0000 - mean_absolute_error: 44032.2617
Epoch 4/300
35/35 [==============================] - 0s 3ms/step - loss: 2056453632.0000 - mean_absolute_error: 44031.3047
Epoch 5/300
35/35 [==============================] - 0s 3ms/step - loss: 2056278912.0000 - mean_absolute_error: 44029.6602
Epoch 6/300
35/35 [==============================] - 0s 3ms/step - loss: 2055967872.0000 - mean_absolute_error: 44026.7383
Epoch 7/300
35/35 [==============================] - 0s 2ms/step - loss: 2055427456.0000 - mean_absolute_error: 44021.6211
Epoch 8/300
35/35 [==============================] - 0s 2ms/step - loss: 2054511872.0000 - mean_absolute_error: 44012.8828
Epoch 9/300
35/35 [==============================] - 0s 3ms/step - loss: 2053064960.0000 - mean_absolute_error: 43999.0391
Epoch 10/300
35/35 [==============================] - 0s 2ms/step - loss: 2050858496.0000 - mean_absolute_error: 43977.7383
Epoch 11/300
35/35 [==============================] - 0s 2ms/step - loss: 2047622656.0000 - mean_absolute_error: 43946.4609
Epoch 12/300
35/35 [==============================] - 0s 3ms/step - loss: 2043120896.0000 - mean_absolute_error: 43902.7773
Epoch 13/300
35/35 [==============================] - 0s 3ms/step - loss: 2037081472.0000 - mean_absolute_error: 43844.4453
Epoch 14/300
35/35 [==============================] - 0s 2ms/step - loss: 2029108352.0000 - mean_absolute_error: 43766.8867
Epoch 15/300
35/35 [==============================] - 0s 2ms/step - loss: 2019038848.0000 - mean_absolute_error: 43668.6328
Epoch 16/300
35/35 [==============================] - 0s 3ms/step - loss: 2006451328.0000 - mean_absolute_error: 43545.3672
Epoch 17/300
35/35 [==============================] - 0s 3ms/step - loss: 1990911232.0000 - mean_absolute_error: 43392.0469
Epoch 18/300
35/35 [==============================] - 0s 2ms/step - loss: 1972647296.0000 - mean_absolute_error: 43211.5586
Epoch 19/300
35/35 [==============================] - 0s 3ms/step - loss: 1950747904.0000 - mean_absolute_error: 42992.9531
Epoch 20/300
35/35 [==============================] - 0s 2ms/step - loss: 1925367680.0000 - mean_absolute_error: 42736.5195
Epoch 21/300
35/35 [==============================] - 0s 3ms/step - loss: 1896316416.0000 - mean_absolute_error: 42442.7422
Epoch 22/300
35/35 [==============================] - 0s 2ms/step - loss: 1863238144.0000 - mean_absolute_error: 42102.8242
Epoch 23/300
35/35 [==============================] - 0s 2ms/step - loss: 1825473280.0000 - mean_absolute_error: 41710.9297
Epoch 24/300
35/35 [==============================] - 0s 3ms/step - loss: 1783774336.0000 - mean_absolute_error: 41272.3359
Epoch 25/300
35/35 [==============================] - 0s 2ms/step - loss: 1737189376.0000 - mean_absolute_error: 40776.9219
Epoch 26/300
35/35 [==============================] - 0s 3ms/step - loss: 1686776576.0000 - mean_absolute_error: 40225.9844
Epoch 27/300
35/35 [==============================] - 0s 2ms/step - loss: 1631814144.0000 - mean_absolute_error: 39615.5781
Epoch 28/300
35/35 [==============================] - 0s 2ms/step - loss: 1572097408.0000 - mean_absolute_error: 38940.4258
Epoch 29/300
35/35 [==============================] - 0s 3ms/step - loss: 1510335872.0000 - mean_absolute_error: 38221.5547
Epoch 30/300
35/35 [==============================] - 0s 2ms/step - loss: 1442852224.0000 - mean_absolute_error: 37415.2305
Epoch 31/300
35/35 [==============================] - 0s 3ms/step - loss: 1373440640.0000 - mean_absolute_error: 36560.7227
Epoch 32/300
35/35 [==============================] - 0s 2ms/step - loss: 1300150016.0000 - mean_absolute_error: 35631.6211
Epoch 33/300
35/35 [==============================] - 0s 3ms/step - loss: 1225380608.0000 - mean_absolute_error: 34648.9922
Epoch 34/300
35/35 [==============================] - 0s 3ms/step - loss: 1148557184.0000 - mean_absolute_error: 33601.4648
Epoch 35/300
35/35 [==============================] - 0s 3ms/step - loss: 1070843328.0000 - mean_absolute_error: 32493.8750
Epoch 36/300
35/35 [==============================] - 0s 3ms/step - loss: 992532416.0000 - mean_absolute_error: 31330.7891
Epoch 37/300
35/35 [==============================] - 0s 3ms/step - loss: 914492224.0000 - mean_absolute_error: 30110.8027
Epoch 38/300
35/35 [==============================] - 0s 3ms/step - loss: 837187648.0000 - mean_absolute_error: 28843.9883
Epoch 39/300
35/35 [==============================] - 0s 3ms/step - loss: 762091776.0000 - mean_absolute_error: 27537.9336
Epoch 40/300
35/35 [==============================] - 0s 3ms/step - loss: 688966272.0000 - mean_absolute_error: 26194.1113
Epoch 41/300
35/35 [==============================] - 0s 3ms/step - loss: 618380864.0000 - mean_absolute_error: 24813.7910
Epoch 42/300
35/35 [==============================] - 0s 3ms/step - loss: 551124032.0000 - mean_absolute_error: 23410.6230
Epoch 43/300
35/35 [==============================] - 0s 3ms/step - loss: 488001472.0000 - mean_absolute_error: 22002.1719
Epoch 44/300
35/35 [==============================] - 0s 3ms/step - loss: 428706752.0000 - mean_absolute_error: 20578.3594
Epoch 45/300
35/35 [==============================] - 0s 3ms/step - loss: 373740256.0000 - mean_absolute_error: 19157.0801
Epoch 46/300
35/35 [==============================] - 0s 3ms/step - loss: 323313184.0000 - mean_absolute_error: 17749.3789
Epoch 47/300
35/35 [==============================] - 0s 3ms/step - loss: 277354336.0000 - mean_absolute_error: 16360.7002
Epoch 48/300
35/35 [==============================] - 0s 3ms/step - loss: 236179744.0000 - mean_absolute_error: 15005.1875
Epoch 49/300
35/35 [==============================] - 0s 3ms/step - loss: 199472816.0000 - mean_absolute_error: 13693.7119
Epoch 50/300
35/35 [==============================] - 0s 2ms/step - loss: 166937968.0000 - mean_absolute_error: 12420.1699
Epoch 51/300
35/35 [==============================] - 0s 3ms/step - loss: 138642768.0000 - mean_absolute_error: 11205.7754
Epoch 52/300
35/35 [==============================] - 0s 3ms/step - loss: 114329960.0000 - mean_absolute_error: 10061.0986
Epoch 53/300
35/35 [==============================] - 0s 3ms/step - loss: 93219392.0000 - mean_absolute_error: 8971.9482
Epoch 54/300
35/35 [==============================] - 0s 2ms/step - loss: 75611408.0000 - mean_absolute_error: 7973.8564
Epoch 55/300
35/35 [==============================] - 0s 2ms/step - loss: 60800924.0000 - mean_absolute_error: 7052.6265
Epoch 56/300
35/35 [==============================] - 0s 2ms/step - loss: 48526016.0000 - mean_absolute_error: 6223.3345
Epoch 57/300
35/35 [==============================] - 0s 2ms/step - loss: 38341664.0000 - mean_absolute_error: 5473.9927
Epoch 58/300
35/35 [==============================] - 0s 2ms/step - loss: 30205522.0000 - mean_absolute_error: 4807.9512
Epoch 59/300
35/35 [==============================] - 0s 2ms/step - loss: 23577546.0000 - mean_absolute_error: 4208.8262
Epoch 60/300
35/35 [==============================] - 0s 2ms/step - loss: 18246048.0000 - mean_absolute_error: 3675.1257
Epoch 61/300
35/35 [==============================] - 0s 2ms/step - loss: 14080530.0000 - mean_absolute_error: 3201.9165
Epoch 62/300
35/35 [==============================] - 0s 2ms/step - loss: 10785157.0000 - mean_absolute_error: 2783.0967
Epoch 63/300
35/35 [==============================] - 0s 2ms/step - loss: 8212280.5000 - mean_absolute_error: 2415.0601
Epoch 64/300
35/35 [==============================] - 0s 2ms/step - loss: 6210754.5000 - mean_absolute_error: 2091.8660
Epoch 65/300
35/35 [==============================] - 0s 2ms/step - loss: 4686876.0000 - mean_absolute_error: 1806.1428
Epoch 66/300
35/35 [==============================] - 0s 3ms/step - loss: 3508282.5000 - mean_absolute_error: 1551.7399
Epoch 67/300

35/35 [==============================] - 0s 2ms/step - loss: 2597089.2500 - mean_absolute_error: 1336.4185
Epoch 68/300
35/35 [==============================] - 0s 2ms/step - loss: 1935603.8750 - mean_absolute_error: 1147.0168
Epoch 69/300
35/35 [==============================] - 0s 2ms/step - loss: 1423186.2500 - mean_absolute_error: 979.0432
Epoch 70/300
35/35 [==============================] - 0s 2ms/step - loss: 1041541.6875 - mean_absolute_error: 833.9843
Epoch 71/300
35/35 [==============================] - 0s 3ms/step - loss: 756785.4375 - mean_absolute_error: 708.3427
Epoch 72/300
35/35 [==============================] - 0s 2ms/step - loss: 548989.7500 - mean_absolute_error: 601.1591
Epoch 73/300
35/35 [==============================] - 0s 2ms/step - loss: 396690.2500 - mean_absolute_error: 507.8387
Epoch 74/300
35/35 [==============================] - 0s 2ms/step - loss: 283846.7188 - mean_absolute_error: 427.0472
Epoch 75/300
35/35 [==============================] - 0s 3ms/step - loss: 200054.0156 - mean_absolute_error: 358.9755
Epoch 76/300
35/35 [==============================] - 0s 2ms/step - loss: 142789.8750 - mean_absolute_error: 301.9110
Epoch 77/300
35/35 [==============================] - 0s 2ms/step - loss: 100198.2656 - mean_absolute_error: 252.0189
Epoch 78/300
35/35 [==============================] - 0s 2ms/step - loss: 69798.0312 - mean_absolute_error: 209.7179
Epoch 79/300
35/35 [==============================] - 0s 2ms/step - loss: 48491.3242 - mean_absolute_error: 174.3359
Epoch 80/300
35/35 [==============================] - 0s 2ms/step - loss: 33474.9766 - mean_absolute_error: 144.6602
Epoch 81/300
35/35 [==============================] - 0s 2ms/step - loss: 23064.7793 - mean_absolute_error: 119.2451
Epoch 82/300
35/35 [==============================] - 0s 3ms/step - loss: 15556.7412 - mean_absolute_error: 98.5114
Epoch 83/300
35/35 [==============================] - 0s 2ms/step - loss: 10583.0684 - mean_absolute_error: 80.8876
Epoch 84/300
35/35 [==============================] - 0s 2ms/step - loss: 7068.9756 - mean_absolute_error: 66.1377
Epoch 85/300
35/35 [==============================] - 0s 2ms/step - loss: 4732.1382 - mean_absolute_error: 53.9104
Epoch 86/300
35/35 [==============================] - 0s 2ms/step - loss: 3123.9937 - mean_absolute_error: 43.9513
Epoch 87/300
35/35 [==============================] - 0s 2ms/step - loss: 2067.1248 - mean_absolute_error: 35.5848
Epoch 88/300
35/35 [==============================] - 0s 3ms/step - loss: 1351.4050 - mean_absolute_error: 28.6810
Epoch 89/300
35/35 [==============================] - 0s 2ms/step - loss: 873.1860 - mean_absolute_error: 22.9038
Epoch 90/300
35/35 [==============================] - 0s 2ms/step - loss: 560.4978 - mean_absolute_error: 18.3884
Epoch 91/300
35/35 [==============================] - 0s 3ms/step - loss: 355.9194 - mean_absolute_error: 14.6617
Epoch 92/300
35/35 [==============================] - 0s 2ms/step - loss: 228.0500 - mean_absolute_error: 11.6366
Epoch 93/300
35/35 [==============================] - 0s 2ms/step - loss: 143.3361 - mean_absolute_error: 9.2513
Epoch 94/300
35/35 [==============================] - 0s 2ms/step - loss: 90.0862 - mean_absolute_error: 7.3500
Epoch 95/300
35/35 [==============================] - 0s 2ms/step - loss: 56.4479 - mean_absolute_error: 5.7875
Epoch 96/300
35/35 [==============================] - 0s 2ms/step - loss: 34.9924 - mean_absolute_error: 4.5750
Epoch 97/300
35/35 [==============================] - 0s 2ms/step - loss: 22.2737 - mean_absolute_error: 3.6458
Epoch 98/300
35/35 [==============================] - 0s 2ms/step - loss: 14.3188 - mean_absolute_error: 2.9248
Epoch 99/300
35/35 [==============================] - 0s 2ms/step - loss: 9.3801 - mean_absolute_error: 2.3790
Epoch 100/300
35/35 [==============================] - 0s 2ms/step - loss: 6.4202 - mean_absolute_error: 1.9775
Epoch 101/300
35/35 [==============================] - 0s 2ms/step - loss: 4.6437 - mean_absolute_error: 1.6848
Epoch 102/300
35/35 [==============================] - 0s 2ms/step - loss: 3.6157 - mean_absolute_error: 1.4916
Epoch 103/300
35/35 [==============================] - 0s 2ms/step - loss: 2.9950 - mean_absolute_error: 1.3566
Epoch 104/300
35/35 [==============================] - 0s 2ms/step - loss: 2.6656 - mean_absolute_error: 1.2901
Epoch 105/300
35/35 [==============================] - 0s 3ms/step - loss: 2.4770 - mean_absolute_error: 1.2449
Epoch 106/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3485 - mean_absolute_error: 1.2156
Epoch 107/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2949 - mean_absolute_error: 1.2039
Epoch 108/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2611 - mean_absolute_error: 1.1972
Epoch 109/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2393 - mean_absolute_error: 1.1941
Epoch 110/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2242 - mean_absolute_error: 1.1907
Epoch 111/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2177 - mean_absolute_error: 1.1888
Epoch 112/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2187 - mean_absolute_error: 1.1886
Epoch 113/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2058 - mean_absolute_error: 1.1851
Epoch 114/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2053 - mean_absolute_error: 1.1845
Epoch 115/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2098 - mean_absolute_error: 1.1873
Epoch 116/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1889 - mean_absolute_error: 1.1814
Epoch 117/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1818 - mean_absolute_error: 1.1799
Epoch 118/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1721 - mean_absolute_error: 1.1784
Epoch 119/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1704 - mean_absolute_error: 1.1773
Epoch 120/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1696 - mean_absolute_error: 1.1766
Epoch 121/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1688 - mean_absolute_error: 1.1784
Epoch 122/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1658 - mean_absolute_error: 1.1767
Epoch 123/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1659 - mean_absolute_error: 1.1764
Epoch 124/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1611 - mean_absolute_error: 1.1769
Epoch 125/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1703 - mean_absolute_error: 1.1810
Epoch 126/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1449 - mean_absolute_error: 1.1731
Epoch 127/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1443 - mean_absolute_error: 1.1729
Epoch 128/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1464 - mean_absolute_error: 1.1732
Epoch 129/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1504 - mean_absolute_error: 1.1746
Epoch 130/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1461 - mean_absolute_error: 1.1728
Epoch 131/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1471 - mean_absolute_error: 1.1745
Epoch 132/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1521 - mean_absolute_error: 1.1753
Epoch 133/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1449 - mean_absolute_error: 1.1739
Epoch 134/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1496 - mean_absolute_error: 1.1748
Epoch 135/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1494 - mean_absolute_error: 1.1758
Epoch 136/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1496 - mean_absolute_error: 1.1732
Epoch 137/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1482 - mean_absolute_error: 1.1729
Epoch 138/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1514 - mean_absolute_error: 1.1764
Epoch 139/300

35/35 [==============================] - 0s 2ms/step - loss: 2.1467 - mean_absolute_error: 1.1732
Epoch 140/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1492 - mean_absolute_error: 1.1743
Epoch 141/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1506 - mean_absolute_error: 1.1754
Epoch 142/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1498 - mean_absolute_error: 1.1733
Epoch 143/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1499 - mean_absolute_error: 1.1749
Epoch 144/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1498 - mean_absolute_error: 1.1750
Epoch 145/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1534 - mean_absolute_error: 1.1758
Epoch 146/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1526 - mean_absolute_error: 1.1762
Epoch 147/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1534 - mean_absolute_error: 1.1753
Epoch 148/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1505 - mean_absolute_error: 1.1730
Epoch 149/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1485 - mean_absolute_error: 1.1736
Epoch 150/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1499 - mean_absolute_error: 1.1735
Epoch 151/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1628 - mean_absolute_error: 1.1802
Epoch 152/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1634 - mean_absolute_error: 1.1793
Epoch 153/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1608 - mean_absolute_error: 1.1796
Epoch 154/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1452 - mean_absolute_error: 1.1744
Epoch 155/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1544 - mean_absolute_error: 1.1742
Epoch 156/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1502 - mean_absolute_error: 1.1743
Epoch 157/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1513 - mean_absolute_error: 1.1761
Epoch 158/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1521 - mean_absolute_error: 1.1746
Epoch 159/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1536 - mean_absolute_error: 1.1778
Epoch 160/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1690 - mean_absolute_error: 1.1789
Epoch 161/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1500 - mean_absolute_error: 1.1729
Epoch 162/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1663 - mean_absolute_error: 1.1804
Epoch 163/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1508 - mean_absolute_error: 1.1758
Epoch 164/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1712 - mean_absolute_error: 1.1772
Epoch 165/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1593 - mean_absolute_error: 1.1791
Epoch 166/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1680 - mean_absolute_error: 1.1794
Epoch 167/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1693 - mean_absolute_error: 1.1825
Epoch 168/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1519 - mean_absolute_error: 1.1752
Epoch 169/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1620 - mean_absolute_error: 1.1779
Epoch 170/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1665 - mean_absolute_error: 1.1801
Epoch 171/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1747 - mean_absolute_error: 1.1774
Epoch 172/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1607 - mean_absolute_error: 1.1778
Epoch 173/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1662 - mean_absolute_error: 1.1764
Epoch 174/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1634 - mean_absolute_error: 1.1790
Epoch 175/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1527 - mean_absolute_error: 1.1762
Epoch 176/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1599 - mean_absolute_error: 1.1759
Epoch 177/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1549 - mean_absolute_error: 1.1754
Epoch 178/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1673 - mean_absolute_error: 1.1803
Epoch 179/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1571 - mean_absolute_error: 1.1799
Epoch 180/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1752 - mean_absolute_error: 1.1782
Epoch 181/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1489 - mean_absolute_error: 1.1744
Epoch 182/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1686 - mean_absolute_error: 1.1783
Epoch 183/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1681 - mean_absolute_error: 1.1840
Epoch 184/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1636 - mean_absolute_error: 1.1757
Epoch 185/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1604 - mean_absolute_error: 1.1777
Epoch 186/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1644 - mean_absolute_error: 1.1765
Epoch 187/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1841 - mean_absolute_error: 1.1839
Epoch 188/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1665 - mean_absolute_error: 1.1803
Epoch 189/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1915 - mean_absolute_error: 1.1911
Epoch 190/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1788 - mean_absolute_error: 1.1783
Epoch 191/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1673 - mean_absolute_error: 1.1807
Epoch 192/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1754 - mean_absolute_error: 1.1836
Epoch 193/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1782 - mean_absolute_error: 1.1795
Epoch 194/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1623 - mean_absolute_error: 1.1824
Epoch 195/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1686 - mean_absolute_error: 1.1797
Epoch 196/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1669 - mean_absolute_error: 1.1821
Epoch 197/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1677 - mean_absolute_error: 1.1780
Epoch 198/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1712 - mean_absolute_error: 1.1814
Epoch 199/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1702 - mean_absolute_error: 1.1814
Epoch 200/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1971 - mean_absolute_error: 1.1891
Epoch 201/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2020 - mean_absolute_error: 1.1906
Epoch 202/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1870 - mean_absolute_error: 1.1883
Epoch 203/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1745 - mean_absolute_error: 1.1797
Epoch 204/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1800 - mean_absolute_error: 1.1830
Epoch 205/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1695 - mean_absolute_error: 1.1784
Epoch 206/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1705 - mean_absolute_error: 1.1771
Epoch 207/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1805 - mean_absolute_error: 1.1804
Epoch 208/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1892 - mean_absolute_error: 1.1811
Epoch 209/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1718 - mean_absolute_error: 1.1874
Epoch 210/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1753 - mean_absolute_error: 1.1754
Epoch 211/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1748 - mean_absolute_error: 1.1819
Epoch 212/300

35/35 [==============================] - 0s 2ms/step - loss: 2.2121 - mean_absolute_error: 1.1833
Epoch 213/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1971 - mean_absolute_error: 1.1904
Epoch 214/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1729 - mean_absolute_error: 1.1830
Epoch 215/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1884 - mean_absolute_error: 1.1855
Epoch 216/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1712 - mean_absolute_error: 1.1836
Epoch 217/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1897 - mean_absolute_error: 1.1851
Epoch 218/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1860 - mean_absolute_error: 1.1809
Epoch 219/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2150 - mean_absolute_error: 1.1919
Epoch 220/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1648 - mean_absolute_error: 1.1707
Epoch 221/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2458 - mean_absolute_error: 1.2007
Epoch 222/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1854 - mean_absolute_error: 1.1816
Epoch 223/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1917 - mean_absolute_error: 1.1891
Epoch 224/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1887 - mean_absolute_error: 1.1764
Epoch 225/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1951 - mean_absolute_error: 1.1882
Epoch 226/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2147 - mean_absolute_error: 1.1911
Epoch 227/300
35/35 [==============================] - 0s 3ms/step - loss: 2.1915 - mean_absolute_error: 1.1868
Epoch 228/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2107 - mean_absolute_error: 1.1896
Epoch 229/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2255 - mean_absolute_error: 1.1906
Epoch 230/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2302 - mean_absolute_error: 1.1877
Epoch 231/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2339 - mean_absolute_error: 1.1935
Epoch 232/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2648 - mean_absolute_error: 1.1999
Epoch 233/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2156 - mean_absolute_error: 1.1894
Epoch 234/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2280 - mean_absolute_error: 1.1894
Epoch 235/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2049 - mean_absolute_error: 1.1900
Epoch 236/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2712 - mean_absolute_error: 1.1924
Epoch 237/300
35/35 [==============================] - 0s 1ms/step - loss: 2.2361 - mean_absolute_error: 1.2090
Epoch 238/300
35/35 [==============================] - 0s 2ms/step - loss: 2.1925 - mean_absolute_error: 1.1837
Epoch 239/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2097 - mean_absolute_error: 1.1839
Epoch 240/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2356 - mean_absolute_error: 1.1982
Epoch 241/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2266 - mean_absolute_error: 1.1871
Epoch 242/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2299 - mean_absolute_error: 1.2035
Epoch 243/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2688 - mean_absolute_error: 1.2032
Epoch 244/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2470 - mean_absolute_error: 1.1929
Epoch 245/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2343 - mean_absolute_error: 1.2066
Epoch 246/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2384 - mean_absolute_error: 1.1981
Epoch 247/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2739 - mean_absolute_error: 1.2062
Epoch 248/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2035 - mean_absolute_error: 1.1869
Epoch 249/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2289 - mean_absolute_error: 1.1872
Epoch 250/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2166 - mean_absolute_error: 1.1941
Epoch 251/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2078 - mean_absolute_error: 1.1983
Epoch 252/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2288 - mean_absolute_error: 1.1946
Epoch 253/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2253 - mean_absolute_error: 1.1858
Epoch 254/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2932 - mean_absolute_error: 1.2004
Epoch 255/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2399 - mean_absolute_error: 1.2018
Epoch 256/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2125 - mean_absolute_error: 1.1877
Epoch 257/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2310 - mean_absolute_error: 1.1958
Epoch 258/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2409 - mean_absolute_error: 1.2077
Epoch 259/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2300 - mean_absolute_error: 1.2017
Epoch 260/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2826 - mean_absolute_error: 1.2001
Epoch 261/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2870 - mean_absolute_error: 1.2140
Epoch 262/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2626 - mean_absolute_error: 1.1980
Epoch 263/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2425 - mean_absolute_error: 1.2054
Epoch 264/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2662 - mean_absolute_error: 1.2025
Epoch 265/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2575 - mean_absolute_error: 1.2051
Epoch 266/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2230 - mean_absolute_error: 1.2011
Epoch 267/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2315 - mean_absolute_error: 1.1874
Epoch 268/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2482 - mean_absolute_error: 1.2019
Epoch 269/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2357 - mean_absolute_error: 1.1998
Epoch 270/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3111 - mean_absolute_error: 1.2163
Epoch 271/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2804 - mean_absolute_error: 1.1990
Epoch 272/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2562 - mean_absolute_error: 1.1950
Epoch 273/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2776 - mean_absolute_error: 1.2082
Epoch 274/300
35/35 [==============================] - 0s 3ms/step - loss: 2.2700 - mean_absolute_error: 1.1957
Epoch 275/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3619 - mean_absolute_error: 1.2423
Epoch 276/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2824 - mean_absolute_error: 1.1945
Epoch 277/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2358 - mean_absolute_error: 1.1893
Epoch 278/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3138 - mean_absolute_error: 1.2101
Epoch 279/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2331 - mean_absolute_error: 1.1929
Epoch 280/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2674 - mean_absolute_error: 1.2045
Epoch 281/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2618 - mean_absolute_error: 1.2133
Epoch 282/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2389 - mean_absolute_error: 1.1978
Epoch 283/300
35/35 [==============================] - 0s 3ms/step - loss: 2.3161 - mean_absolute_error: 1.2080
Epoch 284/300
35/35 [==============================] - 0s 2ms/step - loss: 2.2582 - mean_absolute_error: 1.2007
Epoch 285/300

35/35 [==============================] - 0s 2ms/step - loss: 2.2771 - mean_absolute_error: 1.2056
Epoch 286/300
35/35 [==============================] - 0s 2ms/step - loss: 2.4066 - mean_absolute_error: 1.2503
Epoch 287/300
35/35 [==============================] - 0s 3ms/step - loss: 2.3768 - mean_absolute_error: 1.2340
Epoch 288/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3587 - mean_absolute_error: 1.2255
Epoch 289/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3367 - mean_absolute_error: 1.2057
Epoch 290/300
35/35 [==============================] - 0s 2ms/step - loss: 2.4214 - mean_absolute_error: 1.2654
Epoch 291/300
35/35 [==============================] - 0s 2ms/step - loss: 2.4072 - mean_absolute_error: 1.2541
Epoch 292/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3761 - mean_absolute_error: 1.2530
Epoch 293/300
35/35 [==============================] - 0s 3ms/step - loss: 2.3885 - mean_absolute_error: 1.2426
Epoch 294/300
35/35 [==============================] - 0s 3ms/step - loss: 2.3307 - mean_absolute_error: 1.2215
Epoch 295/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3526 - mean_absolute_error: 1.2265
Epoch 296/300
35/35 [==============================] - 0s 2ms/step - loss: 2.4138 - mean_absolute_error: 1.2518
Epoch 297/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3202 - mean_absolute_error: 1.2125
Epoch 298/300
35/35 [==============================] - 0s 2ms/step - loss: 2.4180 - mean_absolute_error: 1.2551
Epoch 299/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3643 - mean_absolute_error: 1.2503
Epoch 300/300
35/35 [==============================] - 0s 2ms/step - loss: 2.3727 - mean_absolute_error: 1.2264
5/5 [==============================] - 0s 4ms/step

In [41]:
ypred=ann.predict(xtest)

5/5 [==============================] - 0s 2ms/step

In [42]:
from sklearn.metrics import r2_score

r2_score(ytest,ypred)

0.9999999739187866